apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: my-dockerhub-username/inventory-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: INSUFFICIENT_STOCK_WARNING
              valueFrom:
                configMapKeyRef:
                  name: inventory-config
                  key: insufficient-stock-warning